### ISSUE TITLE
Incorrect anchor for subscribction booster

### ISSUE THREAD

**Issue by bslabiak** [blockfrost/blockfrost.dev#56]
Steps to reproduce:

1. Open https://blockfrost.dev/overview/plans-and-billing
2. Click "Subscription Boosts" (https://blockfrost.dev/overview/plans-and-billing#subscription-boosts)" 
    link under "Upgrading plan" section

Actual Results:
Nothing happend. Anchor is not working.

**Comment by slowbackspace** [comment]
ahh nevermind, I clicked the wrong thing
